markdown: kramdown

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock

assets:
  prefix: ""
  digest: false

gems:
  - jekyll-assets

